# We have a conf and classes directory, add to BBPATH
BBPATH .= ":${LAYERDIR}"

# We have recipes-* directories, add to BBFILES
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
            ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "meta-learningYocto"
BBFILE_PATTERN_meta-learningYocto = "^${LAYERDIR}/"
BBFILE_PRIORITY_meta-learningYocto = "6"

LAYERDEPENDS_meta-learningYocto = "core"
LAYERSERIES_COMPAT_meta-learningYocto = "scarthgap" 
