# BBLAYERS configuration for Raspberry Pi 4. 
# This file was created to the project Rising Embedded OS.

# POKY_BBLAYERS_CONF_VERSION is increased each time build/conf/bblayers.conf
# changes incompatibly
POKY_BBLAYERS_CONF_VERSION = "2"

BBPATH = "${TOPDIR}"
BBFILES ?= ""
BBLAYERS ?= " \
  /home/yocto/workspace/boards/rpi4/poky/meta \
  /home/yocto/workspace/boards/rpi4/poky/meta-poky \
  /home/yocto/workspace/boards/rpi4/poky/meta-yocto-bsp \
  /home/yocto/workspace/boards/rpi4/meta-openembedded/meta-oe \  
  /home/yocto/workspace/boards/rpi4/meta-openembedded/meta-python \
  /home/yocto/workspace/boards/rpi4/meta-openembedded/meta-networking \
  /home/yocto/workspace/boards/rpi4/meta-openembedded/meta-filesystems \
  /home/yocto/workspace/boards/rpi4/meta-raspberrypi \
  /home/yocto/workspace/boards/rpi4/meta-rising-embedded-os \
  "
BBLAYERS_NON_REMOVABLE ?= " \
  /home/yocto/workspace/boards/rpi4/poky/meta \
  /home/yocto/workspace/boards/rpi4/poky/meta-poky \
"