# BBLAYERS configuration for AML-S905X-CC (Libre Computer)
BBLAYERS ?= " \
  /home/yocto/workspace/poky/meta \
  /home/yocto/workspace/poky/meta-poky \
  /home/yocto/workspace/meta-openembedded/meta-oe \
  /home/yocto/workspace/meta-amlogic \
"
BBLAYERS_NON_REMOVABLE ?= " \
  /home/yocto/workspace/poky/meta \
  /home/yocto/workspace/poky/meta-poky \
"